BASE_URL_A: https://playwright.dev
BASE_URL_B: https://www.aigodlike.com

OPENAI_API_KEY: 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

# 数据库连接配置信息
mysql:
  host: 127.0.0.1
  user: root
  password: root
  database: testDB
  port: 3306