BASE_URL_A: https://playwright.dev
BASE_URL_B: https://jekip.github.io/login

OPENAI_API_KEY: sk-EJxxxxx

# 数据库连接配置信息
mysql:
  host: 127.0.0.1
  user: root
  password: root
  database: testDB
  port: 3306
